apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:oracle
        ports:
        - containerPort: 3306
        volumeMounts:
          - name:  mysql-persistent-storage
            mountPath:  /var/lib/mysql
        env:
          - name:  MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  mysql-secret
                key:  mysql-password
          - name:  MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  mysql-secret
                key:  user-password
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name:  mysql-service
spec:
  selector:
    app:  mysql
  type:
  ports:
  - name:  mysql-service
    port:  3306
    targetPort:  3306
  
